# Generated by Django 4.1.3 on 2022-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demonstrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('fatherName', models.CharField(max_length=15)),
                ('motherName', models.CharField(max_length=15)),
                ('gender', models.BooleanField()),
                ('homeAddress', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('college', models.CharField(choices=[('التربية', 'التربية'), ('الآداب والعلوم الإنسانية', 'الآداب والعلوم الإنسانية'), ('الهندسة المعلوماتية', 'الهندسة المعلوماتية'), ('الطب', 'الطب'), ('العلوم', 'العلوم'), ('الهندسة الميكانيكية والكهربائية', 'الهندسة الميكانيكية والكهربائية')], max_length=50)),
                ('section', models.CharField(choices=[('التربية', (('الصحة النفسية', 'الصحة النفسية'), ('دبلوم التأهيل التربوي', 'دبلوم التأهيل التربوي')))], max_length=50)),
                ('specialization', models.CharField(choices=[('دبلوم التأهيل التربوي', (('علم النفس التربوي', 'علم النفس التربوي'), ('التربية العامة وفلسفة التربية', 'التربية العامة وفلسفة التربية')))], max_length=50)),
                ('dispatchCountry', models.CharField(max_length=50)),
                ('dispatchUniversity', models.CharField(max_length=50)),
                ('dispatchDate', models.DateField()),
                ('dispatchDuration', models.IntegerField()),
                ('dispatchType', models.CharField(max_length=20)),
            ],
        ),
    ]
