# Generated by Django 4.1.3 on 2022-12-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstrator',
            name='college',
            field=models.CharField(choices=[('A', 'ABOD')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='section',
            field=models.CharField(choices=[('A', [('B', 'BOD')])], max_length=50),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='specialization',
            field=models.CharField(choices=[('B', [('O', 'OD')])], max_length=50),
        ),
    ]
