# Generated by Django 4.1.3 on 2022-12-07 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_demonstrator_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstrator',
            name='phoneNumber',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$', 'accept only phone numbers')]),
        ),
    ]
