# Generated by Django 4.1.3 on 2022-12-25 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_demonstrator_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisionNumber', models.IntegerField(null=True)),
                ('decisionDate', models.DateField(null=True)),
                ('decisionType', models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10, null=True)),
                ('requiredCertificate', models.CharField(choices=[('language', 'لغة'), ('master', 'ماجستير'), ('ph.d', 'دكتوراه')], max_length=10, null=True)),
                ('dispatchType', models.CharField(choices=[('inner', 'داخلي'), ('outer', 'خارجي')], max_length=10, null=True)),
                ('alimony', models.CharField(choices=[('grant', 'منحة'), ('seat', 'مقعد')], max_length=25, null=True)),
                ('dispatchCountry', models.CharField(max_length=100, null=True)),
                ('dispatchUniversity', models.CharField(max_length=100, null=True)),
                ('dispatchEndDate', models.DateField(null=True)),
                ('backDate', models.DateField(null=True)),
                ('innerSupervisor', models.CharField(max_length=50, null=True)),
                ('outerSupervisor', models.CharField(max_length=50, null=True)),
                ('lastReport', models.TextField(null=True)),
                ('lastReportDate', models.DateField(null=True)),
                ('defenseDate', models.DateField(null=True)),
                ('gettingCertificateDate', models.DateField(null=True)),
                ('commencementDate', models.DateField(null=True)),
                ('atDisposalOfUniversityDate', models.DateField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisionNumber', models.IntegerField(null=True)),
                ('decisionDate', models.DateField(null=True)),
                ('decisionType', models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10, null=True)),
                ('dispatchDecisionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='app.dispatchdecision')),
            ],
        ),
        migrations.CreateModel(
            name='NominaitionDecision',
            fields=[
                ('decisionId', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nominationDecision', serialize=False, to='app.demonstrator')),
                ('decisionNumber', models.IntegerField(null=True)),
                ('decisionDate', models.DateField(null=True)),
                ('decisionType', models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDegree',
            fields=[
                ('id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='universityDegree', serialize=False, to='app.demonstrator')),
                ('university', models.CharField(max_length=100, null=True)),
                ('section', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}[-][0-9]{4}$', 'in format yyyy-yyyy')])),
                ('average', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='dispatchCountry',
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='dispatchDate',
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='dispatchDuration',
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='dispatchType',
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='dispatchUniversity',
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='homeAddress',
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='section',
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='commencementAfterNominationDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='contestAnnouncementDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='currentAdjective',
            field=models.CharField(choices=[('demonstrator', 'معيد'), ('returning', 'عائد'), ('envoy', 'موفد'), ('returning demonstrator', 'معيد عائد'), ('loathes', 'مستنكف'), ('Transfer outside the university', 'نقل خارج الجامعة'), ('end services', 'انهاء خدمات'), ('resigned', 'انهاء بحكم المستقيل')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='home',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='maritalStatus',
            field=models.CharField(choices=[('married', 'متزوج'), ('unmarried', 'أعزب')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='militarySituation',
            field=models.CharField(choices=[('delayed', 'مؤجل'), ('laid off', 'مسرح')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='mobile',
            field=models.CharField(max_length=25, null=True, validators=[django.core.validators.RegexValidator('^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$', 'accept only mobile numbers')]),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='nominationReason',
            field=models.CharField(choices=[('contest', 'مسابقة'), ('First graduate', 'خريج أول')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='residence',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='secion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='telephone',
            field=models.CharField(max_length=25, null=True, validators=[django.core.validators.RegexValidator('^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$', 'accept only mobile numbers')]),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='college',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='fatherName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='motherName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RegularizationDecision',
            fields=[
                ('decisionId', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regularizationDecision', serialize=False, to='app.dispatchdecision')),
                ('decisionNumber', models.IntegerField(null=True)),
                ('decisionDate', models.DateField(null=True)),
                ('decisionType', models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newUniversity', models.CharField(max_length=100, null=True)),
                ('dispatchDecisionNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universityChange', to='app.dispatchdecision')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newSpecialization', models.CharField(max_length=100, null=True)),
                ('dispatchDecisionNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specializationChange', to='app.dispatchdecision')),
            ],
        ),
        migrations.CreateModel(
            name='GraduateStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('diploma', 'دبلوم'), ('master', 'ماجستير'), ('ph.d', 'دكتوراه')], max_length=10, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('college', models.CharField(max_length=100, null=True)),
                ('section', models.CharField(max_length=100, null=True)),
                ('specialzaion', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}[-][0-9]{4}$', 'in format yyyy-yyyy')])),
                ('average', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduateStudies', to='app.demonstrator')),
            ],
        ),
        migrations.CreateModel(
            name='Freeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisionNumber', models.IntegerField(null=True)),
                ('decisionDate', models.DateField(null=True)),
                ('decisionType', models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10, null=True)),
                ('extensionDecisionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freeze', to='app.extension')),
            ],
        ),
        migrations.CreateModel(
            name='DurationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatchDecisionNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='durationChange', to='app.dispatchdecision')),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('dispatchDuration', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatchDuration', to='app.dispatchdecision')),
                ('extensionDuration', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensionDuration', to='app.extension')),
                ('freezeDuration', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freezeDuration', to='app.freeze')),
                ('languageCourseDuration', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languageCourseDuration', to='app.dispatchdecision')),
                ('newDuration', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newDuration', to='app.durationchange')),
            ],
        ),
        migrations.AddField(
            model_name='dispatchdecision',
            name='studentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatchDecision', to='app.demonstrator'),
        ),
        migrations.CreateModel(
            name='CertificateOfExcellence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', 'سنة أولى'), ('2', 'سنة ثانية'), ('3', 'سنة ثالثة'), ('4', 'سنة رابعة'), ('5', 'سنة خامسة'), ('6', 'سنة سادسة'), ('g', 'تخرج')], max_length=1, null=True)),
                ('degree', models.CharField(choices=[('1', 'الأول'), ('2', 'الثاني'), ('3', 'الثالث')], max_length=1, null=True)),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificateOfExcellence', to='app.demonstrator')),
            ],
        ),
        migrations.CreateModel(
            name='AlimonyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newAlimony', models.CharField(choices=[('grant', 'منحة'), ('seat', 'مقعد')], max_length=25, null=True)),
                ('dispatchDecisionNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimonyChange', to='app.dispatchdecision')),
            ],
        ),
        migrations.CreateModel(
            name='AdjectiveChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisionNumber', models.IntegerField(null=True)),
                ('decisionDate', models.DateField(null=True)),
                ('decisionType', models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10, null=True)),
                ('adjective', models.CharField(choices=[('demonstrator', 'معيد'), ('returning', 'عائد'), ('envoy', 'موفد'), ('returning demonstrator', 'معيد عائد'), ('loathes', 'مستنكف'), ('Transfer outside the university', 'نقل خارج الجامعة'), ('end services', 'انهاء خدمات'), ('resigned', 'انهاء بحكم المستقيل')], max_length=50, null=True)),
                ('reason', models.TextField(null=True)),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjectiveChange', to='app.demonstrator')),
            ],
        ),
    ]
