# Generated by Django 4.1.4 on 2022-12-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_adjectivechange_adjective_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominaitiondecision',
            old_name='decisionId',
            new_name='nominaitionDecision',
        ),
        migrations.RenameField(
            model_name='universitydegree',
            old_name='id',
            new_name='universityDegree',
        ),
    ]
