# Generated by Django 4.1.4 on 2022-12-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_decisionid_nominaitiondecision_nominaitiondecision_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NominaitionDecision',
            new_name='NominationDecision',
        ),
        migrations.RenameField(
            model_name='nominationdecision',
            old_name='nominaitionDecision',
            new_name='nominationDecision',
        ),
    ]
