# Generated by Django 4.1.4 on 2022-12-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_universitydegree_universitydegreecollege'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NominationDecision',
            new_name='Nomination',
        ),
        migrations.RenameField(
            model_name='duration',
            old_name='day',
            new_name='duratioYear',
        ),
        migrations.RenameField(
            model_name='duration',
            old_name='month',
            new_name='durationDay',
        ),
        migrations.RenameField(
            model_name='duration',
            old_name='year',
            new_name='durationMonth',
        ),
        migrations.RenameField(
            model_name='extension',
            old_name='decisionDate',
            new_name='extensionDecisionDate',
        ),
        migrations.RenameField(
            model_name='extension',
            old_name='decisionNumber',
            new_name='extensionDecisionNumber',
        ),
        migrations.RenameField(
            model_name='extension',
            old_name='decisionType',
            new_name='extensionDecisionType',
        ),
        migrations.RenameField(
            model_name='freeze',
            old_name='decisionDate',
            new_name='freezeDecisionDate',
        ),
        migrations.RenameField(
            model_name='freeze',
            old_name='decisionNumber',
            new_name='freezeDecisionNumber',
        ),
        migrations.RenameField(
            model_name='freeze',
            old_name='decisionType',
            new_name='freezeDecisionType',
        ),
        migrations.RenameField(
            model_name='regularizationdecision',
            old_name='decisionDate',
            new_name='regularizationDecisionDate',
        ),
        migrations.RenameField(
            model_name='regularizationdecision',
            old_name='notes',
            new_name='regularizationDecisionNotes',
        ),
        migrations.RenameField(
            model_name='regularizationdecision',
            old_name='decisionNumber',
            new_name='regularizationDecisionNumber',
        ),
        migrations.RenameField(
            model_name='regularizationdecision',
            old_name='decisionType',
            new_name='regularizationDecisionType',
        ),
        migrations.RemoveField(
            model_name='alimonychange',
            name='dispatchDecisionNumber',
        ),
        migrations.RemoveField(
            model_name='durationchange',
            name='dispatchDecisionNumber',
        ),
        migrations.RemoveField(
            model_name='regularizationdecision',
            name='decisionId',
        ),
        migrations.RemoveField(
            model_name='specializationchange',
            name='dispatchDecisionNumber',
        ),
        migrations.RemoveField(
            model_name='universitychange',
            name='dispatchDecisionNumber',
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='currentAdjective',
            field=models.CharField(choices=[('demonstrator', 'معيد'), ('returning', 'عائد'), ('envoy', 'موفد'), ('returning demonstrator', 'معيد عائد'), ('loathes', 'مستنكف'), ('Transfer outside the university', 'نقل خارج الجامعة'), ('end services', 'انهاء خدمات'), ('resigned', 'انهاء بحكم المستقيل')], default='demonstrator', max_length=50),
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DispatchDecisionNumber', models.IntegerField(blank=True, null=True)),
                ('DispatchDecisionDate', models.DateField(blank=True, null=True)),
                ('DispatchDecisionType', models.CharField(blank=True, choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10, null=True)),
                ('requiredCertificate', models.CharField(blank=True, choices=[('language', 'لغة'), ('master', 'ماجستير'), ('ph.d', 'دكتوراه')], max_length=10, null=True)),
                ('dispatchType', models.CharField(blank=True, choices=[('inner', 'داخلي'), ('outer', 'خارجي')], max_length=10, null=True)),
                ('alimony', models.CharField(blank=True, choices=[('grant', 'منحة'), ('seat', 'مقعد')], max_length=25, null=True)),
                ('dispatchCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatchUniversity', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatchEndDate', models.DateField(blank=True, null=True)),
                ('backDate', models.DateField(blank=True, null=True)),
                ('innerSupervisor', models.CharField(blank=True, max_length=50, null=True)),
                ('outerSupervisor', models.CharField(blank=True, max_length=50, null=True)),
                ('lastReport', models.TextField(blank=True, null=True)),
                ('lastReportDate', models.DateField(blank=True, null=True)),
                ('defenseDate', models.DateField(blank=True, null=True)),
                ('gettingCertificateDate', models.DateField(blank=True, null=True)),
                ('commencementDate', models.DateField(blank=True, null=True)),
                ('atDisposalOfUniversityDate', models.DateField(blank=True, null=True)),
                ('DispatchNotes', models.TextField(blank=True, null=True)),
                ('studentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatchDecision', to='app.demonstrator')),
            ],
        ),
        migrations.AddField(
            model_name='alimonychange',
            name='dispatchDecisionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimonyChange', to='app.dispatch'),
        ),
        migrations.AddField(
            model_name='durationchange',
            name='dispatchDecisionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='durationChange', to='app.dispatch'),
        ),
        migrations.AddField(
            model_name='regularizationdecision',
            name='regularizationDecisionId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regularizationDecision', serialize=False, to='app.dispatch'),
        ),
        migrations.AddField(
            model_name='specializationchange',
            name='dispatchDecisionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specializationChange', to='app.dispatch'),
        ),
        migrations.AddField(
            model_name='universitychange',
            name='dispatchDecisionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universityChange', to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='dispatchDuration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatchDuration', to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='languageCourseDuration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languageCourseDuration', to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='dispatchDecisionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='app.dispatch'),
        ),
        migrations.DeleteModel(
            name='DispatchDecision',
        ),
    ]
