# Generated by Django 4.1.4 on 2022-12-29 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_nominationdecision_nomination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regularization',
            fields=[
                ('regularizationDecisionId', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regularization', serialize=False, to='app.dispatch')),
                ('regularizationDecisionNumber', models.IntegerField(blank=True, null=True)),
                ('regularizationDecisionDate', models.DateField(blank=True, null=True)),
                ('regularizationDecisionType', models.CharField(blank=True, choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10, null=True)),
                ('regularizationDecisionNotes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dispatch',
            old_name='DispatchDecisionDate',
            new_name='dispatchDecisionDate',
        ),
        migrations.RenameField(
            model_name='dispatch',
            old_name='DispatchDecisionNumber',
            new_name='dispatchDecisionNumber',
        ),
        migrations.RenameField(
            model_name='dispatch',
            old_name='DispatchDecisionType',
            new_name='dispatchDecisionType',
        ),
        migrations.RenameField(
            model_name='dispatch',
            old_name='DispatchNotes',
            new_name='dispatchNotes',
        ),
        migrations.RenameField(
            model_name='duration',
            old_name='duratioYear',
            new_name='durationYear',
        ),
        migrations.AlterField(
            model_name='adjectivechange',
            name='adjectiveChangeAdjective',
            field=models.CharField(blank=True, choices=[('demonstrator', 'معيد'), ('returning', 'عائد'), ('envoy', 'موفد'), ('returning demonstrator', 'معيد عائد'), ('loathes', 'مستنكف'), ('transfer outside the university', 'نقل خارج الجامعة'), ('end services', 'انهاء خدمات'), ('resigned', 'انهاء بحكم المستقيل')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='currentAdjective',
            field=models.CharField(blank=True, choices=[('demonstrator', 'معيد'), ('returning', 'عائد'), ('envoy', 'موفد'), ('returning demonstrator', 'معيد عائد'), ('loathes', 'مستنكف'), ('transfer outside the university', 'نقل خارج الجامعة'), ('end services', 'انهاء خدمات'), ('resigned', 'انهاء بحكم المستقيل')], default='demonstrator', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='mobile',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$', 'أدخل رقم هاتف جوال')]),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='telephone',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('^([0-9]{3}[-]?)?[0-9]{7}$', 'أدخل رقم هاتف أرضي')]),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='studentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='app.demonstrator'),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesYear',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}[-][0-9]{4}$', 'أدخل السنة الجامعية بتنسيق: YYYY-YYYY مثل 2022-2023')]),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeYear',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}[-][0-9]{4}$', 'أدخل السنة الجامعية بتنسيق: YYYY-YYYY مثل 2022-2023')]),
        ),
        migrations.DeleteModel(
            name='RegularizationDecision',
        ),
    ]
