# Generated by Django 4.1.4 on 2023-02-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_regularization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='lastReport',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='lastReportDate',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, null=True)),
                ('reportDate', models.DateField(blank=True, null=True)),
                ('dispatchDecisionId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='app.dispatch')),
            ],
        ),
    ]
