# Generated by Django 4.1.4 on 2023-02-17 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_remove_dispatch_lastreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionsCollege', models.CharField(blank=True, max_length=100, null=True)),
                ('userId', models.ManyToManyField(blank=True, null=True, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
