# Generated by Django 4.1.4 on 2023-02-21 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='userId',
            field=models.ManyToManyField(blank=True, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
