# Generated by Django 4.1.4 on 2023-02-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_permissions_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='dispatchDurationDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='dispatchDurationMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='dispatchDurationYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='languageCourseDurationDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='languageCourseDurationMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='languageCourseDurationYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='durationchange',
            name='durationChangeDurationDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='durationchange',
            name='durationChangeDurationMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='durationchange',
            name='durationChangeDurationYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='extensionDurationDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='extensionDurationMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='extensionDurationYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freeze',
            name='freezeDurationDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freeze',
            name='freezeDurationMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freeze',
            name='freezeDurationYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
