# Generated by Django 4.1.4 on 2023-03-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_adjectivechange_createddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstrator',
            name='fatherName',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='motherName',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='name',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
