# Generated by Django 4.1.4 on 2023-03-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_demonstrator_fathername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demonstrator',
            name='secion',
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='section',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='college',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='home',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='language',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='residence',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='specialization',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='university',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
