# Generated by Django 4.1.4 on 2023-03-18 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_demonstrator_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstrator',
            name='contestAnnouncementDate',
            field=models.DateField(default='2000-02-02'),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='currentAdjective',
            field=models.CharField(choices=[('demonstrator', 'معيد'), ('returning', 'عائد'), ('envoy', 'موفد'), ('returning demonstrator', 'معيد عائد'), ('loathes', 'مستنكف'), ('transfer outside the university', 'نقل خارج الجامعة'), ('end services', 'انهاء خدمات'), ('resigned', 'انهاء بحكم المستقيل')], default='demonstrator', max_length=50),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='email',
            field=models.EmailField(default='a@aaa.aaa', max_length=254),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='maritalStatus',
            field=models.CharField(choices=[('married', 'متزوج'), ('unmarried', 'أعزب')], default='unmarried', max_length=10),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='militarySituation',
            field=models.CharField(choices=[('delayed', 'مؤجل'), ('laid off', 'مسرح')], default='delayed', max_length=25),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='mobile',
            field=models.CharField(default='0937777777', max_length=25, validators=[django.core.validators.RegexValidator('^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$', 'أدخل رقم هاتف جوال')]),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='nominationReason',
            field=models.CharField(choices=[('contest', 'مسابقة'), ('First graduate', 'خريج أول')], default='contest', max_length=25),
        ),
    ]
