# Generated by Django 4.1.4 on 2023-03-18 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_demonstrator_contestannouncementdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstrator',
            name='birthDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='contestAnnouncementDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='maritalStatus',
            field=models.CharField(choices=[('married', 'متزوج'), ('unmarried', 'أعزب')], max_length=10),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='militarySituation',
            field=models.CharField(choices=[('delayed', 'مؤجل'), ('laid off', 'مسرح')], max_length=25),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='mobile',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$', 'أدخل رقم هاتف جوال')]),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='nominationReason',
            field=models.CharField(choices=[('contest', 'مسابقة'), ('First graduate', 'خريج أول')], max_length=25),
        ),
    ]
