# Generated by Django 4.1.4 on 2023-03-18 22:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_demonstrator_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='universityDegree', serialize=False, to='app.demonstrator'),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeAverage',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeCollege',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeSection',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeUniversity',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeYear',
            field=models.CharField(default='2000-2001', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{4}[-][0-9]{4}$', 'أدخل السنة الجامعية بتنسيق: YYYY-YYYY مثل 2022-2023')]),
        ),
    ]
