# Generated by Django 4.1.4 on 2023-03-18 22:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_universitydegree_universitydegree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateofexcellence',
            name='certificateOfExcellenceDegree',
            field=models.CharField(choices=[('1', 'الأول'), ('2', 'الثاني'), ('3', 'الثالث')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='certificateofexcellence',
            name='certificateOfExcellenceYear',
            field=models.CharField(choices=[('1', 'سنة أولى'), ('2', 'سنة ثانية'), ('3', 'سنة ثالثة'), ('4', 'سنة رابعة'), ('5', 'سنة خامسة'), ('6', 'سنة سادسة'), ('g', 'تخرج')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='certificateofexcellence',
            name='studentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='certificateOfExcellence', to='app.demonstrator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesAverage',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesCollege',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesDegree',
            field=models.CharField(choices=[('diploma', 'دبلوم'), ('master', 'ماجستير'), ('ph.d', 'دكتوراه')], default='diploma', max_length=10),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesSection',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesSpecialzaion',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesUniversity',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesYear',
            field=models.CharField(default='2000-2001', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{4}[-][0-9]{4}$', 'أدخل السنة الجامعية بتنسيق: YYYY-YYYY مثل 2022-2023')]),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='studentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='graduateStudies', to='app.demonstrator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominationDecision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nominationDecision', serialize=False, to='app.demonstrator'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominationDecisionDate',
            field=models.DateField(default='2000-02-02'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominationDecisionNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominationDecisionType',
            field=models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], default='s', max_length=10),
        ),
    ]
