# Generated by Django 4.1.4 on 2023-03-18 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_certificateofexcellence_certificateofexcellencedegree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateofexcellence',
            name='certificateOfExcellenceDegree',
            field=models.CharField(choices=[('1', 'الأول'), ('2', 'الثاني'), ('3', 'الثالث')], max_length=1),
        ),
        migrations.AlterField(
            model_name='certificateofexcellence',
            name='certificateOfExcellenceYear',
            field=models.CharField(choices=[('1', 'سنة أولى'), ('2', 'سنة ثانية'), ('3', 'سنة ثالثة'), ('4', 'سنة رابعة'), ('5', 'سنة خامسة'), ('6', 'سنة سادسة'), ('g', 'تخرج')], max_length=1),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesAverage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesCollege',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesDegree',
            field=models.CharField(choices=[('diploma', 'دبلوم'), ('master', 'ماجستير'), ('ph.d', 'دكتوراه')], max_length=10),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesSection',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesSpecialzaion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesUniversity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesYear',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{4}[-][0-9]{4}$', 'أدخل السنة الجامعية بتنسيق: YYYY-YYYY مثل 2022-2023')]),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominationDecisionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominationDecisionNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominationDecisionType',
            field=models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeAverage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeCollege',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeSection',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeUniversity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='universityDegreeYear',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{4}[-][0-9]{4}$', 'أدخل السنة الجامعية بتنسيق: YYYY-YYYY مثل 2022-2023')]),
        ),
    ]
