# Generated by Django 4.1.4 on 2023-03-18 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0026_alter_certificateofexcellence_certificateofexcellencedegree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjectivechange',
            name='adjectiveChangeAdjective',
            field=models.CharField(choices=[('demonstrator', 'معيد'), ('returning', 'عائد'), ('envoy', 'موفد'), ('returning demonstrator', 'معيد عائد'), ('loathes', 'مستنكف'), ('transfer outside the university', 'نقل خارج الجامعة'), ('end services', 'انهاء خدمات'), ('resigned', 'انهاء بحكم المستقيل')], default='demonstrator', max_length=50),
        ),
        migrations.AlterField(
            model_name='adjectivechange',
            name='adjectiveChangeDecisionDate',
            field=models.DateField(default='2000-02-02'),
        ),
        migrations.AlterField(
            model_name='adjectivechange',
            name='adjectiveChangeDecisionNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='adjectivechange',
            name='adjectiveChangeDecisionType',
            field=models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], default='s', max_length=10),
        ),
        migrations.AlterField(
            model_name='adjectivechange',
            name='studentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adjectiveChange', to='app.demonstrator'),
        ),
        migrations.AlterField(
            model_name='lastpull',
            name='lastPullDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lastpull',
            name='userId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lastPull', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='permissionsCollege',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='userId',
            field=models.ManyToManyField(default=1, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
