# Generated by Django 4.1.4 on 2023-03-18 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_alter_adjectivechange_adjectivechangeadjective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjectivechange',
            name='adjectiveChangeAdjective',
            field=models.CharField(choices=[('demonstrator', 'معيد'), ('returning', 'عائد'), ('envoy', 'موفد'), ('returning demonstrator', 'معيد عائد'), ('loathes', 'مستنكف'), ('transfer outside the university', 'نقل خارج الجامعة'), ('end services', 'انهاء خدمات'), ('resigned', 'انهاء بحكم المستقيل')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adjectivechange',
            name='adjectiveChangeDecisionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='adjectivechange',
            name='adjectiveChangeDecisionNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adjectivechange',
            name='adjectiveChangeDecisionType',
            field=models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adjectivechange',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjectiveChange', to='app.demonstrator'),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='contestAnnouncementDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='alimony',
            field=models.CharField(choices=[('grant', 'منحة'), ('seat', 'مقعد')], default='grant', max_length=25),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchCountry',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDecisionDate',
            field=models.DateField(default='2000-02-02'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDecisionNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDecisionType',
            field=models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], default='s', max_length=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDurationDay',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDurationMonth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDurationYear',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchType',
            field=models.CharField(choices=[('inner', 'داخلي'), ('outer', 'خارجي')], default='inner', max_length=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchUniversity',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='languageCourseDurationDay',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='languageCourseDurationMonth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='languageCourseDurationYear',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='requiredCertificate',
            field=models.CharField(choices=[('language', 'لغة'), ('master', 'ماجستير'), ('ph.d', 'دكتوراه')], default='master', max_length=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='studentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='app.demonstrator'),
        ),
        migrations.AlterField(
            model_name='lastpull',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lastPull', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='permissionsCollege',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='userId',
            field=models.ManyToManyField(related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
