# Generated by Django 4.1.4 on 2023-03-18 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_adjectivechange_adjectivechangeadjective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimonychange',
            name='dispatchDecisionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alimonyChange', to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='alimonychange',
            name='newAlimony',
            field=models.CharField(choices=[('grant', 'منحة'), ('seat', 'مقعد')], default='grant', max_length=25),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='alimony',
            field=models.CharField(choices=[('grant', 'منحة'), ('seat', 'مقعد')], max_length=25),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchCountry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDecisionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDecisionNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDecisionType',
            field=models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDurationDay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDurationMonth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchDurationYear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchType',
            field=models.CharField(choices=[('inner', 'داخلي'), ('outer', 'خارجي')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchUniversity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='languageCourseDurationDay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='languageCourseDurationMonth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='languageCourseDurationYear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='requiredCertificate',
            field=models.CharField(choices=[('language', 'لغة'), ('master', 'ماجستير'), ('ph.d', 'دكتوراه')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='app.demonstrator'),
        ),
        migrations.AlterField(
            model_name='durationchange',
            name='dispatchDecisionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='durationChange', to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='durationchange',
            name='durationChangeDurationDay',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='durationchange',
            name='durationChangeDurationMonth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='durationchange',
            name='durationChangeDurationYear',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='extension',
            name='dispatchDecisionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extensionDecisionDate',
            field=models.DateField(default='2000-02-02'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extensionDecisionNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extensionDecisionType',
            field=models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], default='s', max_length=10),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extensionDurationDay',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extensionDurationMonth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extensionDurationYear',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='dispatchDecisionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='freeze', to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='freezeDecisionDate',
            field=models.DateField(default='2000-02-02'),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='freezeDecisionNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='freezeDecisionType',
            field=models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], default='s', max_length=10),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='freezeDurationDay',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='freezeDurationMonth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='freezeDurationYear',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='regularization',
            name='regularizationDecisionDate',
            field=models.DateField(default='2000-02-02'),
        ),
        migrations.AlterField(
            model_name='regularization',
            name='regularizationDecisionId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regularization', serialize=False, to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='regularization',
            name='regularizationDecisionNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='regularization',
            name='regularizationDecisionType',
            field=models.CharField(choices=[('s', 'ش.ع'), ('o', 'و'), ('b', 'ب')], default='s', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='dispatchDecisionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportDate',
            field=models.DateField(default='2000-02-02'),
        ),
        migrations.AlterField(
            model_name='specializationchange',
            name='dispatchDecisionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specializationChange', to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='specializationchange',
            name='newSpecialization',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='universitychange',
            name='dispatchDecisionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='universityChange', to='app.dispatch'),
        ),
        migrations.AlterField(
            model_name='universitychange',
            name='newUniversity',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
