# Generated by Django 4.1.4 on 2023-03-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_alimonychange_dispatchdecisionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='languageCourseDurationDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='languageCourseDurationMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='languageCourseDurationYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
