# Generated by Django 4.1.4 on 2023-03-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_dispatch_languagecoursedurationday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstrator',
            name='currentAdjective',
            field=models.CharField(blank=True, choices=[('demonstrator', 'معيد'), ('returning', 'عائد'), ('envoy', 'موفد'), ('returning demonstrator', 'معيد عائد'), ('loathes', 'مستنكف'), ('transfer outside the university', 'نقل خارج الجامعة'), ('end services', 'انهاء خدمات'), ('resigned', 'انهاء بحكم المستقيل')], default='demonstrator', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesAverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesCollege',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesSection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesSpecialzaion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesUniversity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
