# Generated by Django 4.1.4 on 2023-03-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_demonstrator_currentadjective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesAverage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesCollege',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesSection',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesSpecialzaion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='graduateStudiesUniversity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
