# Generated by Django 4.1.4 on 2023-03-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_graduatestudies_graduatestudiesaverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstrator',
            name='nominationReason',
            field=models.CharField(blank=True, choices=[('contest', 'مسابقة'), ('First graduate', 'خريج أول')], max_length=25, null=True),
        ),
    ]
