# Generated by Django 4.1.7 on 2023-04-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_dispatch_dispatchbegindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatchBeginDate',
            field=models.DateField(),
        ),
    ]
