# Generated by Django 4.2.1 on 2023-05-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_adjectivechange_deleteddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=255)),
                ('objectId', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='adjectivechange',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='alimonychange',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='certificateofexcellence',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='demonstrator',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='durationchange',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='freeze',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='graduatestudies',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='regularization',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='specializationchange',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='universitychange',
            name='deletedDate',
        ),
        migrations.RemoveField(
            model_name='universitydegree',
            name='deletedDate',
        ),
    ]
