# Generated by Django 4.1.3 on 2023-05-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(default='data', max_length=255),
            preserve_default=False,
        ),
    ]
