# Generated by Django 4.1.4 on 2023-06-16 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_uploadedfile_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedobjects',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
