# Generated by Django 4.1.4 on 2023-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_deletedobjects_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjectivechange',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimonychange',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificateofexcellence',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletedobjects',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatch',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='durationchange',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extension',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeze',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduatestudies',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomination',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissions',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularization',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specializationchange',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitychange',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitydegree',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
