# Generated by Django 4.1.4 on 2023-06-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_adjectivechange_islastmodifiedbyotherside_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjectivechange',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='alimonychange',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='certificateofexcellence',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='deletedobjects',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='demonstrator',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='durationchange',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='graduatestudies',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='regularization',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='specializationchange',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='universitychange',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='universitydegree',
            name='isLastModifiedByOtherSide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
