# Generated by Django 4.1.4 on 2023-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_adjectivechange_islastmodifiedbyotherside_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjectivechange',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='alimonychange',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='certificateofexcellence',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='deletedobjects',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='demonstrator',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='dispatch',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='durationchange',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='extension',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='freeze',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='graduatestudies',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='nomination',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='permissions',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='regularization',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='specializationchange',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='universitychange',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.RenameField(
            model_name='universitydegree',
            old_name='isLastModifiedByOtherSide',
            new_name='isOffline',
        ),
        migrations.AddField(
            model_name='lastpull',
            name='waitingMerge',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
