# Generated by Django 4.2.1 on 2023-07-14 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0050_alter_permissions_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='userId',
            field=models.ManyToManyField(blank=True, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
