# Generated by Django 4.2.1 on 2023-07-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0051_alter_permissions_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSynchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isOffline', models.BooleanField(blank=True, default=False, null=True)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userSynchronization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
