# Generated by Django 4.2.1 on 2023-08-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_usersynchronization'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjectivechange',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alimonychange',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='certificateofexcellence',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='demonstrator',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='durationchange',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='freeze',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='graduatestudies',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='regularization',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='specializationchange',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='universitychange',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='universitydegree',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usersynchronization',
            name='modifiedByOffline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
