# Generated by Django 4.2.1 on 2023-08-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_adjectivechange_modifiedbyoffline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularization',
            name='emailSent',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
