# Generated by Django 4.2.1 on 2023-08-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_regularization_emailsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularization',
            name='emailSent',
        ),
        migrations.AddField(
            model_name='extension',
            name='emailSent',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
