from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('download/', views.pullData, name='download'),
    path('downloadDocumentation/', views.downloadDocumentation, name='downloadDocumentation'),
    path('upload/', views.pushData, name='upload_file'),
    path('send/', views.Email, name='email'),
    path('sendEmails/', views.SendEmails, name='send'),
    path('register/', views.Register, name='register'),
    path('test/', views.Test, name='test'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('insert/', views.DemonstratorInsert2, name='insert'),
    path('query/', views.QueryDemonstrator, name='query'),
    path('allDemonstrators/', views.getAllDemonstrators, name='allDemonstrators'),
    path('demonstrator/<int:id>/', views.getDemonstrator, name='demonstrator'),
    path('dispatch/<int:demonId>/', views.DispatchInsert, name='dispatch'),
    path('getdispatch/<int:dispatchId>/', views.getDispatch, name='getdispatch'),
    path('extinsert/<int:dispatchId>/<int:demonId>/', views.ExtensionInsert, name='extinsert'),
    path('extensionEmail/<int:dispatchId>/<int:demonId>/<int:extensionId>/', views.SendExtensionEmail, name='extensionEmail'),
    path('freinsert/<int:dispatchId>/<int:demonId>/', views.FreezeInsert, name='freinsert'),
    path('reportinsert/<int:dispatchId>/<int:demonId>/', views.ReportInsert, name='reportinsert'),
    path('updateExtension/<int:id>/<int:demonId>/', views.UpdateExtension, name='updateExtension'),
    path('updateFreeze/<int:id>/<int:demonId>/', views.UpdateFreeze, name='updateFreeze'),
    path('updateDispatch/<int:id>/<int:demonId>/', views.UpdateDispatch, name='updateDispatch'),
    path('updateUnv/<int:id>/<int:demonId>/', views.UpdateUniversityDegree, name='updateUnv'),
    path('updateGrad/<int:id>/<int:demonId>/', views.UpdateGraduateStudies, name='updateGrad'),
    path('updateDemon/<int:id>/', views.UpdateDemonstrator, name='updateDemon'),
    path('deleteExtension/<int:id>/<int:demonId>/', views.DeleteExtension, name='deleteExtension'),
    path('deleteFreeze/<int:id>/<int:demonId>/', views.DeleteFreeze, name='deleteFreeze'),
    path('deleteDispatch/<int:id>/<int:demonId>/', views.DeleteDispatch, name='deleteDispatch'),
    path('deleteUnv/<int:id>/<int:demonId>/', views.DeleteUniversityDegree, name='deleteUnv'),
    path('deleteGrad/<int:id>/<int:demonId>/', views.DeleteGraduateStudies, name='deleteGrad'),
    path('deleteCert/<int:id>/<int:demonId>/', views.DeleteCertificateOfExcellence, name='deleteCert'),
    path('deleteDemon/<int:id>/', views.DeleteDemonstrator, name='deleteDemon'),
    path('getAllEmails/', views.GetAllEmails, name='getAllEmails'),
    path('getLateEmails/', views.GetLateEmails, name='getLateEmails'),
    path('getCollegeEmails/', views.GetCollegeEmails, name='getCollegeEmails'),
    path('reportinsert/<int:demonId>/', views.GraduateStudiesDegreeInsert, name='insertGraduate'),
    path('insertExcellence/<int:demonId>/', views.CertificateExcellenceYearInsert, name='insertExcellence'),
    path('durationInsert/<int:dispatchId>/<int:demonId>/', views.DurationChangeInsert, name='durationInsert'),
    path('getAllUsers/', views.GetAllUsers, name='getAllUsers'),
    path('gett/', views.do_something, name='gett'),
    path('test/', views.Test, name='test'),
    path('permissions/', views.permissions_list, name='permissions_list'),
    path('permissions/<int:pk>/', views.permissions_detail, name='permissions_detail'),
    path('permissions/delete/<int:pk>/', views.DeletePermission, name='permissions_delete'),
    path('permissions/update/<int:pk>/', views.UpdatePermission, name='permissions_update'),
    path('permissions/insert/', views.PermissionInsert, name='permissions_insert'),
    path('users/', views.GetAllUsers, name='user_list'),
    path('users/<int:id>', views.GetUser, name='permissions_insert'),
    path('users/update/<int:id>', views.UpdateUser, name='permissions_insert'),
    path('users/delete/<int:id>', views.DeleteUser, name='permissions_insert'),
    path('users/changePassword/<int:id>', views.UpdateUserPassword, name='permissions_insert'),
    path('users/makeUserAdmin/<int:id>', views.MakeUserAdmin, name='permissions_insert'),
    path('about-us', views.About, name='about_us'),


]